<?php

namespace SavvyAI\Features\Training;

use SavvyAI\Base\Reply;
use OpenAI\Laravel\Facades\OpenAI;

/**
 * Summarizes text segments into statements
 *
 * Segments are generated by the Segmenter class and passed to the openAI completions API.
 * These statements wil be ready to be turned into vectors by the Vectorizer class.
 *
 * Class Summarizer
 * @author Selvin Ortiz <selvin@savvyai.com>
 * @author Brennen Phippen <brennen@savvyai.com>
 * @package SavvyAI\Savvy
 */
class Summarizer
{
    public function summarize(string $text, int $maxTokens = 2500): Reply
    {
        $prompt = view('prompts.summarize', ['text' => $text])->render();

        $result = OpenAI::completions()->create([
            'model'             => 'text-davinci-003',
            'temperature'       => 0,
            'top_p'             => .5,
            'frequency_penalty' => .5,
            'presence_penalty'  => 0,
            'max_tokens'        => $maxTokens,
            'prompt'            => trim($prompt),
        ]);

        return new Reply($result, []);
    }
}
